### ISSUE TITLE
Erreur 401

### ISSUE THREAD

**Issue by r3z3** [Scrat95220/DomoticzLinky#1]
Merci pour cette alternative au plugin DomoticzLinky
Après avoir généré Token et PRM, et paramétré le fichier de conf avec les éléments attendus, je me prends ce genre d'erreur :
{'code': 401, 'msg': 'Unauthorized', 'hdrs': <http.client.HTTPMessage object at 0x76008f10>, 'fp': <http.client.HTTPResponse object at 0x76008470>, 'file': <http.client.HTTPResponse object at 0x76008470>, 'name': '<urllib response>', 'delete': False, '_closer': <tempfile._TemporaryFileCloser object at 0x76008c50>, 'url': 'http://192.168.1.220:8080/json.htm?type=command&param=setused&idx=865&switchtype=SUBTYPE_VALUE&used=true&options=RGlzYWJsZUxvZ0F1dG9VcGRhdGU6dHJ1ZTtBZGREQkxvZ0VudHJ5OnRydWU%3D'}
A ton avis ??

**Comment by Scrat95220** [comment]
Tu utilises quelle version de Domoticz?
Si c'est la 2023.2 essai de cocher "autoriser l'authentification Basic-Auth sur du pur HTTP (API seulement)" dans Paramètres/Securité

**Comment by r3z3** [comment]
Je confirme que l'activation de ce paramètre permet un bon fonctionnement du script !
Merci Scrat95220 !!
